version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/home/app/src
      - ./pom.xml:/home/app/pom.xml
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/vollmed_api
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed_api
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
